FROM local-only/dag-installer:0.1.0

LABEL IMAGE="dag-breast-density-classification"
LABEL VERSION="0.1.0"
LABEL CI_IGNORE="False"

COPY files/dag_breast_density_classification.py /tmp/dags/
COPY files/bdc /tmp/dags/bdc