FROM local-only/dag-installer:0.1.0

LABEL IMAGE="dag-bdc-federated"
LABEL VERSION="0.1.0"
LABEL CI_IGNORE="False"

COPY files/dag_bdc_federated.py /tmp/dags/
COPY files/bdc_federated /tmp/dags/bdc_federated